[project]
name = "proyecto-final-de-semestre"
version = "0.1.0"
description = "Proyecto final para familiarizarse con Django"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.8",
]
